<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Site Map  Page 1 - Generated by www.xml-sitemaps.com</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style type="text/css">
body {
background-color: #DDD;
font: normal 80%  "Trebuchet MS", "Helvetica", sans-serif;
margin:0;
text-align:center;
}
#cont{
margin:auto;
width:800px;
text-align:left;
}
a:link,a:visited {
color: #0180AF;
text-decoration: underline;
}
a:hover {
color: #666;
}
h1 {
background-color:#fff;
padding:20px;
color:#00AEEF;
text-align:left;
font-size:32px;
margin:0px;
}
h3 {
font-size:12px;
background-color:#B8DCE9;
margin:0px;
padding:10px;
}
h3 a {
float:right;
font-weight:normal;
display:block;
}
th {
text-align:center;
background-color:#00AEEF;
color:#fff;
padding:4px;
font-weight:normal;
font-size:12px;
}
td {
font-size:12px;
padding:3px;
text-align:left;
}
tr {background: #fff}
tr:nth-child(odd) {background: #f0f0f0}
#footer {
background-color:#B8DCE9;
padding:10px;
}
.pager,.pager a {
background-color:#00AEEF;
color:#fff;
padding:3px;
}
.lhead {
background-color:#fff;
padding:3px;
font-weight:bold;
font-size:16px;
}
.lpart {
background-color:#f0f0f0;
padding:0px;
}
.lpage {
font:normal 12px verdana;
}
.lcount {
background-color:#00AEEF;
color:#fff;
padding:2px;
margin:2px;
font:bold 12px verdana;
}
a.aemphasis {
color:#009;
font-weight:bold;
}
</style>

</head>
<body>
<div id="cont">
<h1>HTML Site Map</h1>
<h3><a href="http://stiedu.net">Homepage</a>
Last updated: 2017, August 15
</h3>


<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr valign="top">
<td class="lpart" colspan="100"><div class="lhead">/
<span class="lcount">11 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/stimuvision" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/stimumission" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/history" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/value" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/ourcampus" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/ourprogram" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/ourfaculty" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/ourgraduates" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/stimugovernance" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/sitemap" title="Site Map  Page 1 - Generated by www.xml-sitemaps.com">Site Map  Page 1 - Generated by www.xml-sitemaps.com</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">auth/
<span class="lcount">2 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/auth/login" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/auth/register" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">authorprofile/
<span class="lcount">3 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/authorprofile/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/authorprofile/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/authorprofile/6" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">coursedetails/
<span class="lcount">17 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/6" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/7" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/8" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/9" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/17" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/18" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/2" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/5" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/10" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/11" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/12" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/15" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/16" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/coursedetails/19" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">courselists/
<span class="lcount">4 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/courselists/19" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/courselists/20" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/courselists/21" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/courselists/22" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">enrollprogram/
<span class="lcount">17 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/6" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/7" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/8" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/9" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/17" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/18" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/2" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/5" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/10" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/11" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/12" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/15" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/16" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/enrollprogram/19" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">eventdetails/
<span class="lcount">8 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/28" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/27" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/26" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/25" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/24" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/23" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/eventdetails/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">facultyprofile/
<span class="lcount">8 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/10" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/9" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/8" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/7" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/5" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/facultyprofile/2" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">graduatelists/
<span class="lcount">2 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/graduatelists/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/graduatelists/0" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">password/
<span class="lcount">1 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/password/email" title="iHoney">iHoney</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">visitorinfo/
<span class="lcount">17 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/6" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/7" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/8" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/9" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/17" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/18" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/2" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/5" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/10" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/11" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/12" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/15" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/16" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfo/19" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

<tr valign="top">
<td class="lbullet">&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td class="lpart" colspan="99"><div class="lhead">visitorinfoadmission/
<span class="lcount">17 pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/6" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/7" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/8" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/9" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/17" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/18" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/1" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/2" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/3" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/4" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/5" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/10" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/11" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/12" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/15" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/16" title="STI Myanmar University">STI Myanmar University</a></td></tr>
<tr><td class="lpage"><a href="http://stiedu.net/visitorinfoadmission/19" title="STI Myanmar University">STI Myanmar University</a></td></tr>
</table>
</td>
</tr>

</table>


<!--
Please note:
You are not allowed to remove the copyright notice below.
Thank you!
www.xml-sitemaps.com
-->
<div id="footer">
Page generated by XML-Sitemaps.com - <a target="_blank" href="https://www.xml-sitemaps.com">Google XML sitemap and html sitemaps generator</a>
|
Copyright &copy; 2005-2015

</div>
</div>
</body>
</html>
